### ISSUE TITLE
unable to load localhost url in the docker container

### ISSUE THREAD

**Issue by mohanzeal** [Mitranim/epdf#4]
I am using this module to generate pdf. Can you please explain anything why it's not loading the localhost url in the docker. Below is the error. Other than localhost all public urls are working. Are there any settings to enable accessing localhost in the docker. 

EPDF error 8ab97c72-d19b-441f-9669-4011e8b7ebfe: Failed to load url: http://localhost:3004/preview/pdf↵    at Future.race.map.error (/usr/local/lib/node_modules/epdf/lib/epdf.js:63:11)↵    at Future.settle (/usr/local/lib/node_modules/epdf/node_modules/posterus/dist/posterus.js:151:26)↵    at Future.finishPending (/usr/local/lib/node_modules/epdf/node_modules/posterus/dist/posterus.js:217:57)↵    at finishPending (/usr/local/lib/node_modules/epdf/node_modules/posterus/dist/posterus.js:301:12)↵    at Scheduler.tick (/usr/local/lib/node_modules/epdf/node_modules/posterus/dist/posterus.js:52:17)↵    at onScheduledTick (/usr/local/lib/node_modules/epdf/node_modules/posterus/dist/posterus.js:75:15)↵    at _combinedTickCallback (internal/process/next_tick.js:131:7)↵    at process._tickCallback (internal/process/next_tick.js:180:9

**Comment by mitranim** [comment]
Can you open that URL in a browser locally?

**Comment by mitranim** [comment]
If I understand correctly, it sounds like the URL works locally but not in a docker container, which is why you're asking about accessing localhost from one. Hmm... I never ran into this issue, so unfortunately I don't recall a solution offhand. Usually when developing multiple services together, you either containerize them all, or none.

**Comment by mohanzeal** [comment]
yes I am able to access the url locally. But any way that's not a big problem though. Since all the public urls are accessible in the docker, when it comes to dev and prod environment there is no problem.

**Comment by mitranim** [comment]
Closing this, as it doesn't look like an Epdf problem, and unfortunately I have no advice to offer.
